keywords:
  urgent:
    - "구조조정"
    - "자진퇴출"
    - "감시대상"
    - "규제"
    - "자본금 증감"
    - "파산"
    - "영업정지"
    - "폐지"
    - "청산"
    - "부도"
    - "상장폐지"
    - "거래정지"
    - "분할"
    - "합병"
    - "영업양수도"
    - "자산양도"
    - "워크아웃"
    - "기업개선약관"
    - "부채재조정"
  watch:
    - "인수합병"
    - "지배구조 변경"
    - "임원 교체"
    - "전략적 제휴"
    - "부실채권"
    - "M&A"
    - "유상증자"
    - "무상증자"
    - "증자"
    - "신주발행"
    - "상호변경"
    - "본점이전"
    - "사업목적변경"
  info:
    - "기업 실적"
    - "배당"
    - "신규 상품"
    - "순환 보직"
    - "공시"
    - "보도자료"
    - "뉴스"
